# Generated by Django 4.2.17 on 2025-05-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='verb',
        ),
    ]
