from django.contrib.auth import views as auth_views
from django.urls import include, path
from .views import views, person_views, tree_views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.home, name='home'),
    path('event/<int:id>/edit', person_views.edit_event, name='edit_event'),
    path('family-event/<int:id>/edit', person_views.edit_family_event, name='edit_family_event'),
    path('register/', views.register, name='register'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('person/find-families-for-dropdown', person_views.families_for_dropdown, name='families_for_dropdown'),
    path('person/<int:id>', person_views.person, name='person'),
    path('person/<int:id>/edit/person', person_views.edit_person, name='edit_person'),
    path('person/<int:id>/edit/relationships', person_views.edit_relationships, name='edit_relationships'),
    path('person/<int:id>/delete', person_views.delete_person, name='delete_person'),
    path('person/<int:id>/event-list', person_views.event_list, name='event_list'),
    path('person/<int:id>/event/add/<str:event_type>', person_views.add_event, name='add_event'),
    path('person/<int:id>/add/partner/<int:family_id>', person_views.add_person_as_partner, name='add_person_as_partner'),
    path('person/<int:id>/add/child', person_views.add_person_as_child, name='add_person_as_child'),
    path('person/<int:id>/add/parent/<str:parent>', person_views.add_person_as_parent, name='add_person_as_parent'),
    path('person/<int:id>/images', person_views.view_images, name='view_images'),
    path('person/<int:id>/images/add', person_views.add_images, name='add_images'),
    path('person/<int:person_id>/images/<int:image_id>/edit', person_views.edit_image, name='edit_image'),
    path('person/<int:person_id>/images/<int:image_id>/delete', person_views.delete_image, name='delete_image'),
    path('person/<int:person_id>/images/<int:image_id>/view', person_views.view_image, name='view_image'),
    path('person/<int:person_id>/images/<int:image_id>/like', person_views.like_image, name='like_image'),
    path('person/<int:person_id>/images/<int:image_id>/comments/add', person_views.image_add_comment, name='image_add_comment'),
    path('person/<int:person_id>/images/<int:image_id>/comments/<int:comment_id>/delete', person_views.image_delete_comment, name='image_delete_comment'),
    path('person/<int:id>/images/change-profile-photo', person_views.change_profile_photo, name='change_profile_photo'),
    path('search/', tree_views.search, name='search'),
    path('search/update-result-row/<int:id>', tree_views.update_search_result_row, name='update_result_row'),
    path('tree/', tree_views.family_tree, name='family_tree'),
    path('tree/<int:id>/view/<int:person_id>', tree_views.view_tree, name='view_tree'),
    path('tree/<int:id>/delete', tree_views.delete_tree, name='delete_tree'),
    path('tree/<int:id>/edit', tree_views.edit_tree, name='edit_tree'),
    path('tree/<int:id>/add-person', person_views.add_person, name='add_person'),
    path('tree/<int:id>/find-for-dropdown', person_views.search_people_for_dropdown, name='search_people_for_dropdown'),
    path('tree/<int:id>/download', tree_views.download_tree, name='download_tree'),
    path('tree/get-list', tree_views.get_tree_list, name='get_tree_list'),
]