from django.urls import path
from .views import views, person_views, tree_views

app_name = "genealogy"
urlpatterns = [
    path('', views.home, name='home'),
    path('community/', views.community, name='community'),
    path('community/user/<int:pk>', views.community_user, name='community_user'),
    path('community/user/<int:pk>/follow', views.follow_user, name='follow_user'),
    path('event/<int:pk>/edit', person_views.edit_event, name='edit_event'),
    path('family-event/<int:pk>/edit', person_views.edit_family_event, name='edit_family_event'),
    path('person/find-families-for-dropdown', person_views.families_for_dropdown, name='families_for_dropdown'),
    path('person/<int:pk>', person_views.person, name='person'),
    path('person/<int:pk>/edit/person', person_views.edit_person, name='edit_person'),
    path('person/<int:pk>/edit/relationships', person_views.edit_relationships, name='edit_relationships'),
    path('person/<int:pk>/delete', person_views.delete_person, name='delete_person'),
    path('person/<int:pk>/event-list', person_views.event_list, name='event_list'),
    path('person/<int:pk>/event/add/<str:event_type>', person_views.add_event, name='add_event'),
    path('person/<int:person_pk>/add/partner/<int:family_pk>', person_views.add_person_as_partner, name='add_person_as_partner'),
    path('person/<int:pk>/add/child', person_views.add_person_as_child, name='add_person_as_child'),
    path('person/<int:pk>/add/parent/<str:parent>', person_views.add_person_as_parent, name='add_person_as_parent'),
    path('person/<int:pk>/images', person_views.view_images, name='view_images'),
    path('person/<int:pk>/images/add', person_views.add_image, name='add_image'),
    path('person/<int:person_pk>/images/<int:image_pk>/edit', person_views.edit_image, name='edit_image'),
    path('person/<int:person_pk>/images/<int:image_pk>/delete', person_views.delete_image, name='delete_image'),
    path('images/<int:pk>/view', person_views.view_image, name='view_image'),
    path('images/<int:pk>/like', person_views.like_image, name='like_image'),
    path('images/<int:pk>/comments/add', person_views.image_add_comment, name='image_add_comment'),
    path('images/<int:image_pk>/comments/<int:comment_pk>/delete', person_views.image_delete_comment, name='image_delete_comment'),
    path('person/<int:pk>/images/change-profile-photo', person_views.change_profile_photo, name='change_profile_photo'),
    path('search/', tree_views.search, name='search'),
    path('search/update-result-row/<int:pk>', tree_views.update_search_result_row, name='update_result_row'),
    path('tree/', tree_views.family_tree, name='family_tree'),
    path('tree/<int:tree_pk>/view/<int:person_pk>', tree_views.view_tree, name='view_tree'),
    path('tree/<int:pk>/delete', tree_views.delete_tree, name='delete_tree'),
    path('tree/<int:pk>/edit', tree_views.edit_tree, name='edit_tree'),
    path('tree/<int:pk>/add-person', person_views.add_person, name='add_person'),
    path('tree/<int:pk>/find-for-dropdown', person_views.search_people_for_dropdown, name='search_people_for_dropdown'),
    path('tree/<int:pk>/download', tree_views.download_tree, name='download_tree'),
    path('tree/get-list', tree_views.get_tree_list, name='get_tree_list'),
]