# Generated by Django 4.2.17 on 2025-02-25 09:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import genealogy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('archive_id', models.CharField(blank=True, max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('web_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to=genealogy.models.users_file_location)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('gedcom_file', models.FileField(blank=True, upload_to=genealogy.models.users_file_location)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('web_link', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('publishing_date', models.CharField(blank=True, max_length=50)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.archive')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to=genealogy.models.users_file_location)),
                ('description', models.TextField(blank=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indi_id', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=10)),
                ('death_cause', models.CharField(blank=True, max_length=100)),
                ('alive', models.BooleanField(default=False)),
                ('added', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_of', to='genealogy.image')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='genealogy.tree')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Image_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.image')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.person')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FamilyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('banns', 'Banns'), ('divorce', 'Divorce'), ('engagement', 'Engagement'), ('marriage', 'Marriage')], max_length=50)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.family')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='husband',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_husband', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='family',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree'),
        ),
        migrations.AddField(
            model_name='family',
            name='wife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_wife', to='genealogy.person'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('baptism', 'Baptism'), ('confirmation', 'Confirmation'), ('cremation', 'Cremation'), ('emigration', 'Emigration'), ('funeral', 'Funeral'), ('graduation', 'Graduation'), ('immigration', 'Immigration'), ('residence', 'Place of Residence'), ('birth', 'Birth'), ('death', 'Death')], max_length=50)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.person')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('A', 'Adopted'), ('B', 'Biological'), ('F', 'Foster'), ('U', 'Unknown')], default='B', max_length=1)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='genealogy.family')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.person')),
            ],
            options={
                'verbose_name_plural': 'Children',
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree'),
        ),
        migrations.AddConstraint(
            model_name='tree',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='User and name combination'),
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('family', 'person'), name='Person and family combination'),
        ),
    ]
