# Generated by Django 4.2.17 on 2025-05-10 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.archive'),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_of', to='genealogy.image'),
        ),
        migrations.AddField(
            model_name='person',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='genealogy.tree'),
        ),
        migrations.AddField(
            model_name='image_person',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.image'),
        ),
        migrations.AddField(
            model_name='image_person',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='image_like',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.image'),
        ),
        migrations.AddField(
            model_name='image_like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image_comment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.image'),
        ),
        migrations.AddField(
            model_name='image_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyevent',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.family'),
        ),
        migrations.AddField(
            model_name='family',
            name='husband',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_husband', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='family',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree'),
        ),
        migrations.AddField(
            model_name='family',
            name='wife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_wife', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='genealogy.family'),
        ),
        migrations.AddField(
            model_name='child',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='archive',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree'),
        ),
        migrations.AddConstraint(
            model_name='tree',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='User and name combination'),
        ),
        migrations.AddConstraint(
            model_name='image_like',
            constraint=models.UniqueConstraint(fields=('user', 'image'), name='unique_user_image_like'),
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('family', 'person'), name='Person and family combination'),
        ),
    ]
