# Generated by Django 4.2.17 on 2025-03-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_image_like_image_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
