# Generated by Django 4.2.17 on 2025-05-11 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genealogy', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_Comment',
            new_name='ImageComment',
        ),
        migrations.RenameModel(
            old_name='Image_Like',
            new_name='ImageLike',
        ),
        migrations.RenameModel(
            old_name='Image_Person',
            new_name='ImagePerson',
        ),
    ]
