# Generated by Django 4.2.17 on 2025-03-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_image_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
