# Generated by Django 4.2.17 on 2025-12-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_rename_image_comment_imagecomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genealogy.person'),
        ),
        migrations.AlterField(
            model_name='familyevent',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_events', to='genealogy.family'),
        ),
    ]
