# Generated by Django 5.1.3 on 2024-11-10 17:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0004_alter_profile_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna'), ('U', 'Unknown')], default='U', max_length=10)),
                ('birth_date', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('death_date', models.CharField(blank=True, max_length=100, null=True)),
                ('death_place', models.CharField(blank=True, max_length=100, null=True)),
                ('death_cause', models.CharField(blank=True, max_length=100, null=True)),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree')),
            ],
        ),
    ]
