# Generated by Django 5.1.3 on 2024-11-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0005_tree_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='gedcom_file',
            field=models.FileField(blank=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
