# Generated by Django 5.1.3 on 2024-11-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0006_tree_gedcom_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='indi_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='individual',
            constraint=models.UniqueConstraint(fields=('tree', 'indi_id'), name='Tree and INDI combination'),
        ),
    ]
