# Generated by Django 5.1.3 on 2024-11-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0007_individual_indi_id_alter_individual_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree'),
        ),
    ]
