# Generated by Django 5.1.3 on 2024-11-11 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0008_alter_individual_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(max_length=20)),
                ('marriage_date', models.CharField(blank=True, max_length=100, null=True)),
                ('marriage_place', models.CharField(blank=True, max_length=100, null=True)),
                ('husband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_husband', to='genealogy.individual')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree')),
                ('wife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_wife', to='genealogy.individual')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genealogy.individual')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genealogy.family')),
            ],
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.UniqueConstraint(fields=('tree', 'family_id'), name='Tree and family combination'),
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('family', 'indi'), name='Individual and family combination'),
        ),
    ]
