# Generated by Django 5.1.3 on 2024-11-11 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0009_family_child_family_tree_and_family_combination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree'),
        ),
    ]
