# Generated by Django 5.1.3 on 2024-11-12 17:26

import genealogy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0010_child_tree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
        migrations.AlterField(
            model_name='tree',
            name='gedcom_file',
            field=models.FileField(blank=True, upload_to=genealogy.models.users_file_location),
        ),
    ]
