# Generated by Django 5.1.3 on 2024-11-14 20:51

import datetime
import genealogy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0011_alter_child_options_alter_family_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='added',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='individual',
            name='last_updated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=genealogy.models.users_file_location),
        ),
    ]
