# Generated by Django 5.1.3 on 2024-11-15 20:58

import genealogy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0012_individual_added_individual_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='gedcom_file',
            field=models.FileField(blank=True, null=True, upload_to=genealogy.models.users_file_location),
        ),
    ]
