# Generated by Django 5.1.3 on 2024-11-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0013_alter_tree_gedcom_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
