# Generated by Django 5.1.3 on 2024-11-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0014_alter_individual_added_alter_individual_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(to='genealogy.individual'),
        ),
    ]
