# Generated by Django 5.1.3 on 2024-11-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0015_family_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='tree',
        ),
    ]
