# Generated by Django 5.1.3 on 2024-11-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0016_remove_child_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='alive',
            field=models.BooleanField(default=False),
        ),
    ]
