# Generated by Django 5.1.3 on 2024-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0017_individual_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='death_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
