# Generated by Django 5.1.3 on 2024-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0018_individual_birth_year_individual_death_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='relation',
            field=models.CharField(choices=[('A', 'Adopted'), ('B', 'Biological'), ('F', 'Foster'), ('U', 'Unknown')], default='B', max_length=1),
        ),
    ]
