# Generated by Django 5.1.3 on 2024-11-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0019_child_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='children',
        ),
    ]
