# Generated by Django 5.1.3 on 2024-11-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0020_remove_family_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genealogy.family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='indi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genealogy.individual'),
        ),
    ]
