# Generated by Django 4.2.16 on 2024-11-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0021_alter_child_family_alter_child_indi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=10),
        ),
    ]
