# Generated by Django 4.2.16 on 2024-12-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0023_alter_individual_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['last_name']},
        ),
    ]
