# Generated by Django 4.2.16 on 2024-12-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0024_alter_individual_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='genealogy.tree'),
        ),
    ]
