# Generated by Django 4.2.16 on 2024-12-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0025_alter_individual_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
