# Generated by Django 4.2.16 on 2024-12-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0026_tree_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tree',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='User and name combination'),
        ),
    ]
