# Generated by Django 4.2.16 on 2024-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0027_tree_user_and_name_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
