# Generated by Django 4.2.16 on 2024-12-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0028_alter_tree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='divorce_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='divorce_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
