# Generated by Django 4.2.16 on 2024-12-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0029_family_divorce_date_family_divorce_place'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='family',
            name='Tree and family combination',
        ),
    ]
