# Generated by Django 4.2.17 on 2025-01-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0030_remove_family_tree_and_family_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('banns', 'Banns'), ('divorce', 'Divorce'), ('engagement', 'Engagement'), ('marriage', 'Marriage'), ('separation', 'Separation')], max_length=50)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.family')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('baptism', 'Baptism'), ('confirmation', 'Confirmation'), ('cremation', 'Cremation'), ('emigration', 'Emigration'), ('funeral', 'Funeral'), ('graduation', 'Graduation'), ('immigration', 'Immigration'), ('profession', 'Profession'), ('residence', 'Place of Residence'), ('religion', 'Religion')], max_length=50)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.individual')),
            ],
        ),
    ]
