# Generated by Django 4.2.17 on 2025-01-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0031_familyevent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
