# Generated by Django 4.2.17 on 2025-01-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0032_alter_family_family_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='divorce_date',
        ),
        migrations.RemoveField(
            model_name='family',
            name='divorce_place',
        ),
        migrations.RemoveField(
            model_name='family',
            name='marriage_date',
        ),
        migrations.RemoveField(
            model_name='family',
            name='marriage_place',
        ),
    ]
