# Generated by Django 4.2.17 on 2025-01-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0033_remove_family_divorce_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='individual',
            new_name='indi',
        ),
    ]
