# Generated by Django 4.2.17 on 2025-01-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0034_rename_individual_event_indi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('baptism', 'Baptism'), ('confirmation', 'Confirmation'), ('cremation', 'Cremation'), ('emigration', 'Emigration'), ('funeral', 'Funeral'), ('graduation', 'Graduation'), ('immigration', 'Immigration'), ('residence', 'Place of Residence')], max_length=50),
        ),
        migrations.AlterField(
            model_name='familyevent',
            name='event_type',
            field=models.CharField(choices=[('banns', 'Banns'), ('divorce', 'Divorce'), ('engagement', 'Engagement'), ('marriage', 'Marriage')], max_length=50),
        ),
    ]
