# Generated by Django 4.2.17 on 2025-01-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0035_alter_event_event_type_alter_familyevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='genealogy.family'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('baptism', 'Baptism'), ('confirmation', 'Confirmation'), ('cremation', 'Cremation'), ('emigration', 'Emigration'), ('funeral', 'Funeral'), ('graduation', 'Graduation'), ('immigration', 'Immigration'), ('residence', 'Place of Residence'), ('birth', 'Birth'), ('death', 'Death')], max_length=50),
        ),
    ]
