# Generated by Django 4.2.17 on 2025-01-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0036_alter_child_family_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='death_place',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='death_year',
        ),
    ]
