# Generated by Django 4.2.17 on 2025-02-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0037_remove_individual_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('archive_id', models.CharField(blank=True, max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('web_link', models.CharField(blank=True, max_length=500)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('web_link', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('publishing_date', models.CharField(blank=True, max_length=50)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.archive')),
            ],
        ),
    ]
