# Generated by Django 4.2.17 on 2025-02-07 10:26

from django.db import migrations, models
import django.db.models.deletion
import genealogy.models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0038_archive_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='genealogy.family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='indi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.individual'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='family',
            name='family_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='familyevent',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='familyevent',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='individual',
            name='death_cause',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individual',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individual',
            name='indi_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='individual',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tree',
            name='gedcom_file',
            field=models.FileField(blank=True, upload_to=genealogy.models.users_file_location),
        ),
    ]
