# Generated by Django 4.2.17 on 2025-02-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0039_alter_child_family_alter_child_indi_alter_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='individual',
            name='Tree and INDI combination',
        ),
    ]
