# Generated by Django 4.2.17 on 2025-02-13 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import genealogy.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genealogy', '0040_remove_individual_tree_and_indi_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to=genealogy.models.users_file_location)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
