# Generated by Django 4.2.17 on 2025-02-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0041_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='profile_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_of', to='genealogy.image'),
        ),
    ]
