# Generated by Django 4.2.17 on 2025-02-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0043_alter_individual_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.image')),
                ('indi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.individual')),
            ],
        ),
    ]
