# Generated by Django 4.2.17 on 2026-02-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Archive or repository', max_length=255)),
                ('date_range', models.CharField(blank=True, help_text='e.g., 1783-1823', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('birth_date', models.CharField(blank=True, help_text='Full or partial date', max_length=20)),
                ('birth_year', models.SmallIntegerField()),
                ('location', models.CharField(blank=True, help_text='Birth location', max_length=200)),
                ('father_first_name', models.CharField(blank=True, max_length=100)),
                ('father_last_name', models.CharField(blank=True, max_length=100)),
                ('father_birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('father_birth_parish', models.CharField(blank=True, max_length=200)),
                ('mother_first_name', models.CharField(blank=True, max_length=100)),
                ('mother_last_name', models.CharField(blank=True, max_length=100)),
                ('mother_birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('mother_birth_parish', models.CharField(blank=True, max_length=200)),
                ('archive_info', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_records', to='records.record')),
            ],
            options={
                'ordering': ['birth_year', 'first_name'],
                'indexes': [models.Index(fields=['birth_year'], name='records_bir_birth_y_592940_idx'), models.Index(fields=['first_name'], name='records_bir_first_n_d7eeab_idx'), models.Index(fields=['father_last_name'], name='records_bir_father__362b6a_idx'), models.Index(fields=['mother_last_name'], name='records_bir_mother__0c22a3_idx')],
            },
        ),
    ]
